### ISSUE TITLE
Alexa search - tunein

### ISSUE THREAD

**Issue by mac-d** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#10]
Hello, the search for Tunein has not worked for a few days.
The voice output works, but no more stations are searched for and played.
greetings Dieter

**Comment by Matten-Matten** [comment]
Moin, kann ich bestätigen auch bei mir funktioniert die Tunein Sendereingabe nicht mehr

**Comment by Matten-Matten** [comment]
Im [iobroker Forum](https://forum.iobroker.net/topic/46746/alexa-2-adapter-probleme-bei-musikwiedergabe/31?page=2) wurde schon etwas darüber gesprochen die haben sowas wie ein workarround gefunden, aber uns in NR bringt das nix. besser wenn das Problen gefunden wird.

**Comment by Matten-Matten** [comment]
Vermutlich ein Amazon Bug...
![TuneIn](https://user-images.githubusercontent.com/32074970/130319980-9b6084cd-e101-4b1e-94bd-e00585f97703.gif)

**Comment by mac-d** [comment]
Ja, ich habe genau das gleiche Phänomen.
Geht weder über node-red noch Amazon.

**Comment by mac-d** [comment]
Hallo, bei funktioniert es wieder über den Befehl "Text Command".
Ist jetzt neu in NR.
![image](https://user-images.githubusercontent.com/13673027/130752637-efc7cab0-c780-42b3-89f0-0722bb9f237a.png)

**Comment by Matten-Matten** [comment]
Ja darüber hat es immer funktioniert. 
Das problem ist ja wenn man via Senderschlüssel den sender starten will. "sXXXXX"

Das ist ein Problem bei Amazon &sie versuchen es schon zu beheben. Ich hatte den Amazon Support kontaktiert.

**Comment by Rain-ZG** [comment]
Solution to this is easy. Use Alexa routine node and in it enter name of radio station

![image](https://user-images.githubusercontent.com/52547452/131300481-2958f0b9-c660-4bf7-8695-f0d4d8916d5a.png)

**Comment by tom666-debug** [comment]
> Solution to this is easy. Use Alexa routine node and in it enter name of radio station
> 

Sadly this approach does not work for a group of devices, e.g. everywhere group.
Handling of device groups seems to be an general issue with the Routine Node.

**Comment by Matten-Matten** [comment]
Probier mal Text to command und schreibe mal sowas wie 
`Spiele *XYZ* von tunein auf *der Gruppen name*`

Beispiel: 
`spiele radio saw von tunein auf alle Geräte`

Damit hab ich das problem der Gruppen umgangen.

Gruß
Matten matten

**Comment by tom666-debug** [comment]
Danke fürs Feedback ... ich hatte das mit dem "Text Command" schon als Workaround übernommen.
Funktioniert - Schöner wäre es trotzdem, wenn man die Funktionalität im "Echo-Node" fixen könnte bzw. dem "Routine-Node" das abspielen auf Device-Gruppen beibringen könnte.

**Comment by bbindreiter** [comment]
I just played around a bit but it's a Alexa API limitation that music cannot be started on a Group. Request is successful but it just doesn't play. Apparently people still want to use the Music Routine Node so I incorporated the hack mentioned by @Matten-Matten. What it does is basically add the group's name to the search request and reroutes the request to the first Echo found. Alexa then proceeds to play music on the group's devices as intended. 

For some search requests however this doesn't work and then I recommend to setup `On Keyword` in the Alexa Account properties. For English put `on` in there. so that the search query basically becomes: `<Music> <OnKeyword> <GroupName>`, for example if you fancy Bruce Springsteen and your group is named `All my Echos` that would be `Bruce Springsteen on All my Echos` and that works pretty well for me.
