### ISSUE TITLE
node-red crashes / restarting

### ISSUE THREAD

**Issue by Saeco** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#113]
I have the issue as discribed:

HW: Raspberry Pi 3 Model B Plus Rev 1.3
OS: Raspbian GNU/Linux 11 (bullseye)
Node-RED version: v3.0.2
Node.js  version: v16.19.0

node-red-contrib-alexa-remote2-applestrudel is installed

To keep Alexa alive I used the flow as shown here:

https://discourse.nodered.org/t/alexa-remote2-stops-talking/32931/45

It's working well, but sometimes noder-red simply is crushing and restarting, because the node (?) is doing unknown things with the websocket. It's really annoying ...

Here's an excerpt of the log:

27 Feb 10:37:48 - [info] [alexa-remote-account:alexaremote1] intialising "alexaremote1" with the PROXY method and saved data...
27 Feb 10:37:51 - [info] [alexa-remote-account:alexaremote1] intialising "alexaremote1" with the PROXY method and saved data...
27 Feb 10:37:51 - [red] Uncaught Exception:
27 Feb 10:37:51 - [error] Error: WebSocket was closed before the connection was established
    at WebSocket.close (/home/pi/.node-red/node_modules/alexa-remote2/node_modules/ws/lib/websocket.js:285:7)
    at AlexaWsMqtt.disconnect (/home/pi/.node-red/node_modules/alexa-remote2/alexa-wsmqtt.js:844:28)
    at AlexaRemoteExt.stop (/home/pi/.node-red/node_modules/alexa-remote2/alexa-remote.js:791:30)
    at AlexaRemoteExt.resetExt (/home/pi/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/lib/alexa-remote-ext.js:593:8)
    at AlexaRemoteAccountNode.resetAlexa (/home/pi/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/nodes/alexa-remote-account.js:392:15)
    at AlexaRemoteAccountNode.initAlexa (/home/pi/.node-red/node_modules/node-red-contrib-alexa-remote2-applestrudel/nodes/alexa-remote-account.js:450:9)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 19min 17.242s CPU time.
nodered.service: Scheduled restart job, restart counter is at 4.
Stopped Node-RED graphical event wiring tool.
nodered.service: Consumed 19min 17.242s CPU time.
Started Node-RED graphical event wiring tool.
27 Feb 10:38:16 - [info]
Welcome to Node-RED

And so on .....

Is this issue known?

**Comment by pebl-hank** [comment]
Same here!

**Comment by dajuly20** [comment]
Same here!

**Comment by dajuly20** [comment]
That should fix it i hope.. 
https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/pull/124

**Comment by pkkrusty** [comment]
HW: Pi 4B
Node-RED version: v3.0.2
Node.js  version: v16.20.0
Linux 5.10.103-v8+ arm LE
OS: Raspbian GNU/Linux 10 (buster)

This morning (probably happening for a while) noticed that my node-red was crashing on startup. Logs weren't very helpful, so disabled flows until the crash stopped, then narrowed it down to the Alexa studel flow. Updated to 5.0.27 just now, and once the config receives the cookie, node-red crashes. Node-red is fine while waiting for me to open the :3456 page and log in.

Is this 3-hour old commit not yet propogated, or is my issue separate? The only notification I get is `  Process: 27894 ExecStart=/usr/bin/env node-red-pi $NODE_OPTIONS $NODE_RED_OPTIONS (code=killed, signal=BUS)`

**Comment by bbindreiter** [comment]
No, the fix is in 5.0.27 although it does not happen for me so I blindly merged it.

If I understood correctly the fix was meant to prevent crashing of Node-Red.

**Comment by pkkrusty** [comment]
Any way for me to help narrow down the issue? Not a coder, but know my way around linux a bit.

**Comment by bbindreiter** [comment]
> Saeco

This flow seems overly complicated. I am triggering the Alexa-Init node every hour and it seems for work well for years. Anyway, with the fix in 5.0.27 it should be gone hopefully. Can you confirm?

<img width="378" alt="image" src="https://user-images.githubusercontent.com/3252801/236297803-a23d3449-7c0e-4b3c-b82e-4e07210b2bf2.png">

**Comment by bbindreiter** [comment]
> Any way for me to help narrow down the issue? Not a coder, but know my way around linux a bit.

Can you please set your node-red logging level to trace and restart. Then at least we know what happened right before it crashed? 

See https://nodered.org/docs/user-guide/runtime/logging 

Thank you!

**Comment by jbilling9** [comment]
I'm having a similar issue. Node-RED has started crashing since updating to v5.0.27, it wasn't happening on the previous version.

Logging level set to trace and shown below (FYI I'm using alexa.amazon.co.uk)

9 Jun 04:18:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Initialization completed
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Open: wss://dp-gw-na.amazon.co.uk/tcomm/
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 307833376131623630372030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030222c22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136227d7d54554e45
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"TUNE","checksum":933344775,"content":{"protocolName":"A:F","parameters":{"AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}}
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Detected protocol A:F
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 2 sent: 307866653838626335322030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136222c22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030227d7d54554e45
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Close: 1006: 
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Retry Connection in 60s
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 3 (Register Connection) sent: 4d53470000036223a69ea266000000010aa5c393000000e447574d204d5347203078303030306234373920307830303030303033622075726e3a74636f6d6d2d656e64706f696e743a6465766963653a646576696365547970653a303a64657669636553657269616c4e756d6265723a3020307830303030303034312075726e3a74636f6d6d2d656e64706f696e743a736572766963653a736572766963654e616d653a446565576562736974654d6573736167696e6753657276696365207b22636f6d6d616e64223a2252454749535445525f434f4e4e454354494f4e227d46414245
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Send First Ping
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 4d5347000000652c35d61b6600000001040ec0510000003d504f4e000000009e2a27139e2a2713000000070052006500670075006c0061007246414245
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"FABE","messageType":"MSG","channel":101,"messageId":741725723,"moreFlag":1711276032,"seq":1,"checksum":68075601,"content":{"messageType":"PON","payloadData":{"type":"Buffer","data":[0,0,0,158,42,39,19,158,42,39,19,0,0,0,7,0,82,0,101,0,103,0,117,0,108,0,97,0,114]}}}
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Received Pong
9 Jun 04:19:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Initialization completed
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Open: wss://dp-gw-na.amazon.co.uk/tcomm/
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 307833376131623630372030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030222c22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136227d7d54554e45
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"TUNE","checksum":933344775,"content":{"protocolName":"A:F","parameters":{"AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}}
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Detected protocol A:F
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 2 sent: 307866653838626335322030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136222c22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030227d7d54554e45
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Close: 1006: 
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Retry Connection in 60s
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 3 (Register Connection) sent: 4d5347000003620fb3cc83660000000117d3a47f000000e447574d204d5347203078303030306234373920307830303030303033622075726e3a74636f6d6d2d656e64706f696e743a6465766963653a646576696365547970653a303a64657669636553657269616c4e756d6265723a3020307830303030303034312075726e3a74636f6d6d2d656e64706f696e743a736572766963653a736572766963654e616d653a446565576562736974654d6573736167696e6753657276696365207b22636f6d6d616e64223a2252454749535445525f434f4e4e454354494f4e227d46414245
9 Jun 04:19:04 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Send First Ping
9 Jun 04:19:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 4d5347000000650efe7dde6600000001ccc86f330000003d504f4e000000009e2a30099e2a3009000000070052006500670075006c0061007246414245
9 Jun 04:19:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"FABE","messageType":"MSG","channel":101,"messageId":251559390,"moreFlag":1711276032,"seq":1,"checksum":3435687731,"content":{"messageType":"PON","payloadData":{"type":"Buffer","data":[0,0,0,158,42,48,9,158,42,48,9,0,0,0,7,0,82,0,101,0,103,0,117,0,108,0,97,0,114]}}}
9 Jun 04:19:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Received Pong
9 Jun 04:19:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Initialization completed
9 Jun 04:20:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Open: wss://dp-gw-na.amazon.co.uk/tcomm/
9 Jun 04:20:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 307833376131623630372030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030222c22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136227d7d54554e45
9 Jun 04:20:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"TUNE","checksum":933344775,"content":{"protocolName":"A:F","parameters":{"AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}}
9 Jun 04:20:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Detected protocol A:F
9 Jun 04:20:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 2 sent: 307866653838626335322030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136222c22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030227d7d54554e45
9 Jun 04:20:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Close: 1006: 
9 Jun 04:20:02 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Retry Connection in 60s
9 Jun 04:20:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 3 (Register Connection) sent: 4d5347000003620468c4506600000001cccb7173000000e447574d204d5347203078303030306234373920307830303030303033622075726e3a74636f6d6d2d656e64706f696e743a6465766963653a646576696365547970653a303a64657669636553657269616c4e756d6265723a3020307830303030303034312075726e3a74636f6d6d2d656e64706f696e743a736572766963653a736572766963654e616d653a446565576562736974654d6573736167696e6753657276696365207b22636f6d6d616e64223a2252454749535445525f434f4e4e454354494f4e227d46414245
9 Jun 04:20:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Send First Ping
9 Jun 04:20:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 4d5347000000652c23b1066600000001f3c1d1500000003d504f4e000000009e2b13269e2b1326000000070052006500670075006c0061007246414245
9 Jun 04:20:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"FABE","messageType":"MSG","channel":101,"messageId":740536582,"moreFlag":1711276032,"seq":1,"checksum":4089565520,"content":{"messageType":"PON","payloadData":{"type":"Buffer","data":[0,0,0,158,43,19,38,158,43,19,38,0,0,0,7,0,82,0,101,0,103,0,117,0,108,0,97,0,114]}}}
9 Jun 04:20:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Received Pong
9 Jun 04:20:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Initialization completed
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Open: wss://dp-gw-na.amazon.co.uk/tcomm/
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Close: 1006: 
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Retry Connection in 60s
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 307833376131623630372030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030222c22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136227d7d54554e45
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"TUNE","checksum":933344775,"content":{"protocolName":"A:F","parameters":{"AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}}
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Detected protocol A:F
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 2 sent: 307866653838626335322030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136222c22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030227d7d54554e45
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 3 (Register Connection) sent: 4d53470000036223a69ea466000000010aa5c593000000e447574d204d5347203078303030306234373920307830303030303033622075726e3a74636f6d6d2d656e64706f696e743a6465766963653a646576696365547970653a303a64657669636553657269616c4e756d6265723a3020307830303030303034312075726e3a74636f6d6d2d656e64706f696e743a736572766963653a736572766963654e616d653a446565576562736974654d6573736167696e6753657276696365207b22636f6d6d616e64223a2252454749535445525f434f4e4e454354494f4e227d46414245
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Send First Ping
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 4d5347000000652b75fb126600000001461d83500000003d504f4e000000009e2b1bf99e2b1bf9000000070052006500670075006c0061007246414245
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"FABE","messageType":"MSG","channel":101,"messageId":729152274,"moreFlag":1711276032,"seq":1,"checksum":1176339280,"content":{"messageType":"PON","payloadData":{"type":"Buffer","data":[0,0,0,158,43,27,249,158,43,27,249,0,0,0,7,0,82,0,101,0,103,0,117,0,108,0,97,0,114]}}}
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Received Pong
9 Jun 04:20:05 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Initialization completed
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Open: wss://dp-gw-na.amazon.co.uk/tcomm/
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 307833376131623630372030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030222c22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136227d7d54554e45
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"TUNE","checksum":933344775,"content":{"protocolName":"A:F","parameters":{"AlphaProtocolHandler.maxFragmentSize":"16000","AlphaProtocolHandler.receiveWindowSize":"16"}}}
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Detected protocol A:F
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 2 sent: 307866653838626335322030783030303030303963207b2270726f746f636f6c4e616d65223a22413a46222c22706172616d6574657273223a7b22416c70686150726f746f636f6c48616e646c65722e7265636569766557696e646f7753697a65223a223136222c22416c70686150726f746f636f6c48616e646c65722e6d6178467261676d656e7453697a65223a223136303030227d7d54554e45
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Close: 1006: 
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Retry Connection in 60s
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: A:F Initialization Msg 3 (Register Connection) sent: 4d5347000003620fb3cc85660000000117d3a67f000000e447574d204d5347203078303030306234373920307830303030303033622075726e3a74636f6d6d2d656e64706f696e743a6465766963653a646576696365547970653a303a64657669636553657269616c4e756d6265723a3020307830303030303034312075726e3a74636f6d6d2d656e64706f696e743a736572766963653a736572766963654e616d653a446565576562736974654d6573736167696e6753657276696365207b22636f6d6d616e64223a2252454749535445525f434f4e4e454354494f4e227d46414245
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Send First Ping
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming RAW message: 4d5347000000650f5282106600000001246b15340000003d504f4e000000009e2bff439e2bff43000000070052006500670075006c0061007246414245
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Incoming message: {"service":"FABE","messageType":"MSG","channel":101,"messageId":257065488,"moreFlag":1711276032,"seq":1,"checksum":610997556,"content":{"messageType":"PON","payloadData":{"type":"Buffer","data":[0,0,0,158,43,255,67,158,43,255,67,0,0,0,7,0,82,0,101,0,103,0,117,0,108,0,97,0,114]}}}
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Received Pong
9 Jun 04:21:03 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Initialization completed
9 Jun 04:21:35 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Initialization not done within 30s
9 Jun 04:21:35 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Close: undefined: undefined
9 Jun 04:21:35 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Retry Connection in 60s
9 Jun 04:21:35 - [debug] [alexa-remote-account:xxxxxx's Alexa Account] Alexa-Remote WS-MQTT: Error: Error: WebSocket was closed before the connection was established
9 Jun 04:21:35 - [red] Uncaught Exception:
9 Jun 04:21:35 - [error] Error: WebSocket was closed before the connection was established
    at WebSocket.close (/config/node-red/node_modules/ws/lib/websocket.js:285:7)
    at Timeout.<anonymous> (/config/node-red/node_modules/alexa-remote2/alexa-wsmqtt.js:231:50)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
[04:21:35] INFO: Service Node-RED exited with code 1 (by signal 0)
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service nginx: stopping
[04:21:35] INFO: Service NGINX exited with code 0 (by signal 0)
s6-rc: info: service nginx successfully stopped
s6-rc: info: service init-nginx: stopping
s6-rc: info: service nodered: stopping
s6-rc: info: service init-nginx successfully stopped
s6-rc: info: service nodered successfully stopped
s6-rc: info: service init-nodered: stopping
s6-rc: info: service init-nodered successfully stopped
s6-rc: info: service init-customizations: stopping
s6-rc: info: service init-customizations successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
