### ISSUE TITLE
amazon page not found

### ISSUE THREAD

**Issue by afv13-15** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#121]
Hei,
i tried to get the authentication via amazon. each time i try to logg in i get this error message:
![image](https://user-images.githubusercontent.com/124370797/229359368-12d0ab5b-9c41-482c-82cd-198fd121b8dd.png)

**Comment by bbindreiter** [comment]
Yes, depending on your configured amazon url this can happen. There were some changes a while ago, see: https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/issues/116

What worked for me right now with pitangui.amazon.com configured was to open http://your-host:3456, go through amazon auth -> enter  2FA code quickly because page refreshes every 10 seconds or so and then got the same page as you. Close Tab, go to http://your-host:3456 again, go through amazon auth and voila, got redirected to http://your-host:3456/cookie-success and within a few seconds node-red changed all nodes to `ready`
