### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by rhamblen** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#159]
I have been working with applestrudel (and its predecessors ) for years.  I recently rebuilt my unraid system and lots my cookie file.
Because we can no longer go into alexa.amazon.com (in my case .co.uk), I cant get a copy of the cookie.  

Any ideas how to get the cookie or authenticate when we dont have a cookie?

When I try to use the authentication settings, I get "Not Tokens in register response" as an error.
Thanks
R.

**Comment by Spazpeker** [comment]
Same problem here cant access Alexa via the web anymore, i do have 2 factor Authentication on my Account

**Comment by alexruffell** [comment]
I may be having a similar issue. While I have my alexa.txt file that holds the cookie info, it doesn't seem to be working any longer. Whether the file is there or not, when I try to log in by going to homeassistantIP:3456 (node blink with message saying to do so), it says Cookie retrieved successfully but it doesn't stick. In other words, as soon as I trigger any Alexa routine it goes back to telling me to log in again.

Any suggestions?

**Comment by alexruffell** [comment]
I just noticed that the path to the amazon.txt file has changed... the addon config folder is in a different location. I am trying to adjust the path from `/config/node-red/amazon.txt` to `/addon_configs/a0d7b954_nodered/amazon.txt` but it is not working. I wonder what the correct relative path is... and whether this is the issue.

**Comment by alexruffell** [comment]
Discord user @wallberjunior gave me the solution... and my integration is working again. The issue is due to the node-red config folder having been moved. 

The cookie file path is: `/config/node-red/amazon.txt` and `config` seems to be symlinked to `/addon_configs/a0d7b954_nodered/` (@wallberjunior mentioned he could not write directly to this location) so the solution is to create a new `node-red` sub-folder and put the amazon.txt file in there.

Resulting file path is: `/addon_configs/a0d7b954_nodered/node-red/amazon.txt`

 move amazon.txt folder to a new folder called node-red created inside the new
