### ISSUE TITLE
ECONNREFUSED working with Alexa

### ISSUE THREAD

**Issue by gtnscebba** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#175]
I'm using alexa-remote2-applestrudel since last year when I was using Raspberry Bullseye amd NodeRed 3.1.0.
Now I use Node Red 3.1.1 on Bookworm.
From that moment on, a series of problems have caused an error in Node Red and analyzing the Syslog I see that the palette that Alexa manages is always involved.
In particular, the error is always a "Connect Econnrefused" whose IP address (never the same, the last one was 52.16.104.93) is always attributable to Amazonows. I have no other palettes that use AWS beyond Alexa.
Node Red goes to "Uncaught Exception": it makes a closure and therefore a restart.
This happens in a non -continuous and absolutely random way: in some days it happens 0 times, in others more than once. When it happens, it can be during the day or at night.
To avoid these continuous problems, unfortunately I had to totally disable the flow.
Since I did it, Node Red has no longer problems.
Is it possible to isolate the problem?

**Comment by Apollon77** [comment]
Do you have any firewalls or Adblockers on DNS level in place or such? Is DNS setup properly? Because in fact ECONNREFUSED means that an ipwas resolved to an yaddress that did not provided the requested service ... so most likely you always need tocheck whats up. And please also maybe post more detailed errors and stack traces
