### ISSUE TITLE
unable to save cookie - changed /config to /homeassistant

### ISSUE THREAD

**Issue by Jmilesy** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#192]
I have been having problems since the update saving the cookie file.

I have changed the address to 'homeassistant/node-red/amazon.txt' from 'config/node-red/amazon.txt'

I have also tried including www in the paths etc  homeassistant/www/node-red/amazon.txt

I have created a blank file in the folder as others have suggested but it will not save the file

I know this is due to the changes in home assistant, but has anyone managed to find a solution?

my set up is:
![image](https://github.com/bbindreiter/node-red-contrib-alexa-remote2-applestrudel/assets/34949583/d92dda09-04d8-4f9d-a3ef-34344dcaa564)

and the error i get is: "ENOENT: no such file or directory, open 'homeassistant/node-red/amazon.txt'"

Many thanks in advance

**Comment by Halkiion** [comment]
I ran into this same issue, turns out Node-RED is not able to see anything outside of its own directory as it's essentially a sandbox, how I fixed it was just by using the addon_configs/local_nodered directory and putting the blank amazon.txt in there, then you can set the file path in Node-RED to /config/amazon.txt. You could use the Filebrowser addon to find this directory.

**Comment by Jmilesy** [comment]
That was perfect, thank you
