### ISSUE TITLE
No speech output

### ISSUE THREAD

**Issue by davemclaughlin** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#2]
I have setup everything and authentication with Amazon etc but there is no sound output from any of my Echo devices.
The debug output from the node shows SUCCESS.
Is there any other setup required for this to work?

**Comment by iainmacthai** [comment]
Yes, I have the same issues too Dave with cakebed & applestrudel, only difference I am doing from the instructions is authenticating with a cookie. Have had this working in he past. Have been away for a few months so had to update a lot of repos that had breaking changes in my absence.

**Comment by bbindreiter** [comment]
I don't think this is an issue with the node, but some mute settings on Alexa.

**Comment by bbindreiter** [comment]
Were you guys able to sort it out?

**Comment by dafi87** [comment]
I'm experiencing the same problem. The nodes were working for multiple days, but now my devices just remain silent. Tested with 3 different Echo devices. The node status says "success" but Alexa just remains silent. It's definitely not a mute setting issue or such because also the Alexa push notification node says "success" but no notification arriving on my phone (this was working fine before too).

**Comment by dafi87** [comment]
@bbindreiter any idea what could cause this behaviour?
Thanks!

**Comment by dafi87** [comment]
I forced a reauthorization now by changing the file path and got it to start working again. I'm still wondering why it never showed an error or auth problem. All nodes came back with "success" while it wasn't working.

**Comment by dafi87** [comment]
Next day it doesn't work anymore. Same problem again. It's just frustrating.
