### ISSUE TITLE
On Device Activity stopped working

### ISSUE THREAD

**Issue by FenvyWorks** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#4]
It just stopped working today, did amazon change things again? can anyone confirm if you are having no response from on device activity too?

**Comment by flashbacck** [comment]
I don't know if your issue is the same as mine. Mine stopped responding, and I noticed the payload has changed significantly. There is no longer a msg.palyload.activityStatus (Which I was checking to see if Amazon processed a message properly), and the msg.payload.description.summary now omits the Alexa Trigger word (e.g. "Alexa"). I had to fix those two issues for me.

**Comment by bbindreiter** [comment]
Thanks for sharing @flashbacck
