### ISSUE TITLE
Add Notification support

### ISSUE THREAD

**Issue by lettore** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#44]
Hello,
not sure if I didn't find the way to do that but I need to send a notification to Alexa, not to the mobile application, but to Echo devices.
The one that leaves the yellow ring blinking.
Maybe it's possible to do it with Routine -> Custom but I really don't know how to work with it.
This is the page with the reference of the api.
https://developer.amazon.com/en-US/docs/alexa/alexa-smart-properties/alexa-for-hospitality-notifications-api.html

**Comment by bwims** [comment]
This is what you need

https://flows.nodered.org/node/node-red-contrib-alexa-notifyme

**Comment by lettore** [comment]
Well no because it works only in English.

Il Lun 17 Gen 2022, 21:28 bwims ***@***.***> ha scritto:

**Comment by bwims** [comment]
Oh ok.  Well, the existence of this routine implies that what you want cannot be achieved in Alexa Remote applestrudel,

Therefore I would suggest you raise an issue with the author of notifyme here https://github.com/bartbutenaers/node-red-contrib-alexa-notifyme

Ask him what he thinks needs to be done to allow for non-English speakers, and if it is possible to make such changes.  If it is, either persuade him to do it or fork the project.

Just my thoughts.

**Comment by lettore** [comment]
Notifyme works using a Skill named Notify Me and that skill is available
only in English, so it's nothing about Notifyme itself.
I wonder why you say it's not possible to send a Notification to Alexa
using Alexa Remote applestrudel as it involves using an API call like any
other functions already implemented.
Actually with Alexa Other node is possible to add a Notification, but only
in the form of a Timer, Reminder or Alarm, it will be so different to add
just the ability to send a message as a Notification to all the devices?

Il giorno lun 17 gen 2022 alle ore 22:59 bwims ***@***.***>
ha scritto:

**Comment by bwims** [comment]
Note that I am not an Alexa programmer, just a Node Red user who's been using this for a couple of years now.  This is what I **_think_** I know.

1.  Amazon change their APIs regularly and don't care what problems they cause hobbyists.  Their APIs are aimed at developers of commercial objects that make money for their companies and Amazon.   Features can and do stop working and need recoding.
2. alexa-remote2-applestrudel is a wrapper for the **_library_** alexa-remote2  maintained here https://github.com/Apollon77/alexa-remote  This is the place to raise an issue, I think.
3. There is indeed a custom feature which works for everything except pushNotifications, and a pushnotification option which appears to succeed, but does nothing at all.   I would guess this has fallen victim to the API changes, because it used to work, for this guy here...  https://discourse.nodered.org/t/alexa-speak-msg-payload-within-a-defined-sentence/32763/4   (this has examples that show you how to construct a Custom routine.)
4. While Notifyme is a skill, it has to be to in order to construct access to the (new?) APIs and access your Echo remotely. But it does work (in the English world).  It is not intended as something you actually access from your Echo, but from Node Red.
5. There is some discussion over at the Notifyme github right now.  https://github.com/bartbutenaers/node-red-contrib-alexa-notifyme/issues/11

Sorry not to have been of more help.

**Comment by bbindreiter** [comment]
I'm sorry, it's a known limitation at the moment. There's an API that some skills use but it's not available via alexa-remote2 (yet).
