### ISSUE TITLE
Node Routine Speak Delay (Sending Status)

### ISSUE THREAD

**Issue by Gml10** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#78]
When I use node alexa-routine with "speak" command sometimes it stays in "sending" status for several seconds or even minutes.

**Comment by xX-Nexus-Xx** [comment]
> When I use node alexa-routine with "speak" command sometimes it stays in "sending" status for several seconds or even minutes.

I'm having the same issues sometimes as well .. usually after a restart of node-red

**Comment by furious1y** [comment]
I get exactly the above, its almost like it's rate limited.
I.e., takes a few minutes for announcements to work, no errors, it's like the node just doesn't process messages.
It's also a problem with notifications too close together - I've got notifications for the front and back doors being opened and closed. Letting the dogs out or deliveries is not an intense storm of notifications, it's just 2 notifications within 20 seconds or multiple minutes.
I get three possibilities:
1. One or two devices announce, then there's a massive delay, then the others trickle in
2. Nothing is said, and I can see the message via debug coming in via MQTT, but then it's just ignored
3. 50% of the notifications get through in a timely fashion, but that's it.

It was even worse as my flows used to have a split so that it sent a TTS to each alexa node individually (I have 5 currently), and that made it pretty much stop working. Changing that to use the "everywhere" node made it better, but it's to the point that I'm looking to use a way older version or just give up on this all.

**Comment by furious1y** [comment]
It appears going back to 5.0.8 allows it to behave better, however there are the odd JSON errors. Rather those than waiting 1-2 minutes for "sending" to finish. So looks like it may be the error handling that can choke the node even if there are split paths.
