### ISSUE TITLE
New Release 5.0.23 Limits ON/OFF commands one every five minutes

### ISSUE THREAD

**Issue by marksmanaz** [bbindreiter/node-red-contrib-alexa-remote2-applestrudel#98]
I know you were trying to limit state queries but ON/OFF commands are now limited also. Is this intentional to the new design? If so you killed a major functionality of this node. 

Thanks

**Comment by bbindreiter** [comment]
Yes it's intentional. People are running scripts that set device states every X minutes to the same value.

The rate limit we've seen in the past is due to too many commands to the Alexa API and we had to limit the requests on our side so they'll lift their limiting maybe again.

Maybe you have a good idea on how to better limit on pur side?

**Comment by bbindreiter** [comment]
Yes, I guess they are rate-limiting per access token, so per user. But the thing is that in general there are millions of requests coming from this node and Amazon doesn't like that, understandably. I'm speculating here, but I guess to them it doesn't make any difference how many requests are coming from each user, all they care about is how many in total.

Hi, can you please describe your use case in detail so I, and everyone else, can think of how this can be finetuned.

**Comment by smcgann99** [comment]
My flow was based on the example music player included with alexa-remote2. 
Having just checked the flow, your limit changes are the least of the porblems now !
After the recent changes by Amazon to prime music service, it is no longer possible to pick a play list, skips are limited and shuffel & repeat comands are now disabled - Thanks Amazon !! ;-(

I guess you may still be able to build in some kind of RBE function, to block repeated (same) messages though.

**Comment by marksmanaz** [comment]
What if you limit the amount of queries and commands per hour rather than each query and command per device per five minutes? Give each user/token 60 queries/command per hour and let them decide how to use them best for their situation.

**Comment by bbindreiter** [comment]
I see your point, but that would still allow polling of device states every 1 minute, which is exactly what we need to get rid of.

**Comment by smcgann99** [comment]
I have for example a node which sets muliple device states back to default values (smart bulbs) and then another following that which turns them all off. I'm assuming that this will not work with the upgrade ?

**Comment by bbindreiter** [comment]
That will work as the request payloads differ.

Requests with the exact same payload will be limited to 1 per 5 minutes. So you could set something to off and then to on again immediately after. But to set it to off again you'd need to wait 5 minutes.

**Comment by marksmanaz** [comment]
> I see your point, but that would still allow polling of device states every 1 minute, which is exactly what we need to get rid of.

But as it is now I could have 5 devices and query them each every five minutes staggered and still have made 60 queries in an hour; one every minute and still make on/off command as well. I know everyone's situation is different but a hourly quota for all requests works better for me and it would limit the over all requests to the API. You are just forcing users to manage their allotted quota for themselves. If they make 60 request in the first five minutes in the hour they are screwed for the rest of the hour. It's up to them to spread them out responsibly.

**Comment by marksmanaz** [comment]
I think the problem is people want to know the state of their sensors and are querying them every 2 to 5 seconds to detect a state change. That is what happens when people use proprietary cloud based devices that  cant be polled locally. In all my installations I use mqtt to monitor state change of sensors locally. I bet if you just limited the state queries that would be enough. On/off request may not be the problem.

**Comment by bbindreiter** [comment]
> I think the problem is people want to know the state of their sensors and are querying them every 2 to 5 seconds to detect a state change. That is what happens when people use proprietary cloud based devices that cant be polled locally. In all my installations I use mqtt to monitor state change of sensors locally. I bet if you just limited the state queries that would be enough. On/off request may not be the problem.

You may be right. In the beginning I planned to only limit queries, but I was explicitly asked to think about set requests as well. For instance, you could set the same value in a script that runs every minute. Now to circumvent the limitation it'd be necessary to remember the last state and only execute the node when it changes. I am willing to lower the 5 minutes of set requests in a future update when we hear back from Amazon.

> Is there anyway to get that type of data from amazon to break down the request types being made?

Not aware of any.

**Comment by smcgann99** [comment]
> Now to circumvent the limitation it'd be necessary to remember the last state and only execute the node when it changes.
I think this is the only way to prevent some bad scripts for spoiling things for everyone ;-)

**Comment by XLixl4snSU** [comment]
Sometimes you come back to a room because you forgot something. Sitting 5 Minutes in the dark is not an option.
But since this is open source everybody who needs more frequent access can just use an old version or remove the restriction in a fork. But I understand that with maintaining such a project comes a certain responsibility.

**Comment by richsimpson** [comment]
My use case that is failing since the update is a Switchbot lock.

I was using the node in one flow to check state every 5 minutes to set a Boolean in Hass. 

For a lock or unlock command, I ignore the status as it may be old and not updated. So a 'goodnight' routine will just try to lock, then immediately attempt to check the state via the node and update in Hass. 5 minutes later the routine will check the Hass state and either do nothing (if it locked ok) or attempt to lock again (if it remains unlocked). 

What I am seeing is the 5-minute update may be repeated when the door locks (within the 5 mins) and so the routine fails. The next 5 minute one also fails. And I then end up in a loop of attempts at offset 5 min intervals that never resolves.

Or If an unlock command has run and not captured the updated status due to the rate limit, the routine sees the state as locked still and doesn't then lock the door - nor check it 5 mins later....

![image](https://user-images.githubusercontent.com/51749826/205605620-b9ad5e60-bd40-4c1b-9203-076af9d3ce13.png)

Any tips to resolve - perhaps longer delay/wait for the auto check? Though any more than 5 mins is really not very good.
